name:  release-ci
defaults:
  run: 
    working-directory: ./Jinget.AzureDevOps.Connector/Jinget.AzureDevOps.RestApi.Connector
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output ./artifacts
    - name: Push
      run: dotnet nuget push ./artifacts/**.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.Jinget_AzureDevOps_Connector_Key}} --skip-duplicate
